### ISSUE TITLE
Create folder

### ISSUE THREAD

**Issue by SaimonL** [Files-com/files-sdk-ruby#11]
Hi does anyone know how to create a folder?

I tried

```ruby
Files::Automation.create(
  automation: 'create_folder',
  trigger: 'realtime', 
  path:'development/test',
  destination: 'success'
)
```

Also tried
```ruby
Files::Automation.create(
  automation: 'create_folder',
  trigger: 'realtime', 
  source: '',
  destination: '',
  trigger_actions: %w[create],
  trigger_action_path: 'development/test/success'
)
```

I always get the same error
`Files::APIError ([HTTP 422] Error saving model.)`

Looking at the document it does not make sense to me.
https://developers.files.com/#create-folder

#### path
Path on which this Automation runs. Supports globs. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.

Thanks

**Comment by romcart** [comment]
Hello @SaimonL,

Sorry about that! It looks like we have a link pointing to the wrong section in our API docs. We'll get that fixed ASAP.

You can access the correct section by going [here](https://developers.files.com/#upload-file) and scrolling down just a bit.

Here is the correct code example for creating a folder:

```
Files::Folder.create(path)
```

**Comment by SaimonL** [comment]
Than you. This is exactly what I need.
