### ISSUE TITLE
Where to set Files API Key

### ISSUE THREAD

**Issue by musa-raza** [Files-com/files-sdk-ruby#13]
I keep getting this error: 

```
Files::AuthenticationError (No Files.com API key provided. Set your API key using "Files.api_key = <API-KEY>". You can generate API keys from the Files.com's web interface. ):
```

I am setting the API Key in my application in config/file.rb with the code snippet:

```
Files.api_key = ENV.fetch('MY_KEY', Rails.application.credentials[:my_key])
```

Is this not the correct way to do it?

**Comment by romcart** [comment]
Hello @musa-raza,

I don't think dropping a file into `config/` will work. You may want to move that to something like `config/initializers/files_com.rb` if this is a rails app.

One other thing we would recommend for troubleshooting purposes is making that file look like this:

```ruby
files_api_key = ENV.fetch('MY_KEY', Rails.application.credentials[:my_key])
warn "Startup: found key #{files_api_key.inspect} for files.com API"
Files.api_key = files_api_key
```

This will allow you to visually verify that the key is being set as expected.

If you have any questions, please feel free to reach out to us via support@files.com.

Best,
Justin Sinclair
Files.com

**Comment by musa-raza** [comment]
Yup, after I posted this issue, I did that and it worked, but thank you for the help! Closing
