### ISSUE TITLE
Gem attempts to loads files from nonexistent location

### ISSUE THREAD

**Issue by parkerfinch** [Files-com/files-sdk-ruby#16]
Hello!

It looks like the change [here](https://github.com/Files-com/files-sdk-ruby/commit/b1c86aacea63756012cd28975e06e107ae98942d) moved from requiring files in the `models` directory to requiring files in the `clients` directory. However, there is no `clients` directory in the gem, so this gem cannot be loaded.

Let me know if I can provide any more info — this issue is preventing us from upgrading our version of this gem past 1.0.188, it would be great to get this fixed!

**Comment by bombino** [comment]
Hi, 

Thanks for the report.  Our team will be looking at this ASAP and we should be able to get a fix for you within the day.  We use the Ruby SDK ourselves in a lot of our internal projects, so this is important to us too.

--Kevin

**Comment by parkerfinch** [comment]
> Hi,
> 
> Thanks for the report. Our team will be looking at this ASAP and we should be able to get a fix for you within the day. We use the Ruby SDK ourselves in a lot of our internal projects, so this is important to us too.
> 
> --Kevin

Great, thank you Kevin!

**Comment by bombino** [comment]
We have a fix rolling through our CI now, expect a new gem version posted within an hour.  We apologize for breaking things!
