### ISSUE TITLE
Upload a whole directory that contain images

### ISSUE THREAD

**Issue by ChunAllen** [Files-com/files-sdk-ruby#18]
I have an image under `public/images/test.jpeg`

I would like to upload the entire `public/images` folder and its contents to `uploads/images` folder in files.com

According here https://github.com/Files-com/files-sdk-ruby/blob/7ed3bdd16d36b5d202cf4c55d6fb6f9116927ddc/lib/files.com/models/file.rb#L169

the `upload_file` accepts `path` and `destination`

I tried this approach

```
dir = File.join(Rails.root, 'public', 'images')
file = File.new(dir)

Files::File.upload_file(file, "uploads/images")
```

But i'm currently getting this error

```

TypeError: no implicit conversion of Symbol into Integer
from /Users/*****/.rvm/gems/ruby-2.6.0/gems/files.com-1.0.43/lib/files.com/models/file_part_upload.rb:64:in `partsize'
```

I also checked the documentation https://github.com/Files-com/files-sdk-ruby/blob/master/docs/file.md#upload-file

and tried this approach

```
dir = File.join(Rails.root, 'public', 'images')

Files::File.create(dir, 
  length: 1, 
  mkdir_parents: true, 
  part: 1, 
  parts: 1, 
  provided_mtime: "2000-01-01T01:00:00Z", 
  restart: 1, 
  size: 1, 
  with_rename: true
)
```

but I'm getting 
```
Files::InvalidRequestError: Bad request
from /Users/***/.rvm/gems/ruby-2.6.0/gems/files.com-1.0.43/lib/files.com/api_client.rb:253:in `handle_error_response'
```

**Comment by zeisler** [comment]
@ChunAllen I'm sorry that you are having trouble with our SDK. I need more time to look into why that method is not working, but in the mean time try the following code snippet. This is how we use the SDK internal so I'm sure it works.

```ruby
file = Files::FIle.new(remote_file_path)
file.mkdir_parents = true
file.write(File.open(local_file_path)
file.close
```

**Comment by ChunAllen** [comment]
Hi @zeisler 

I tried running it in `Ruby 2.7.1`  and I can upload the image

### Gemfile
```
ruby '2.7.1'

gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
```

```
dir = File.join(Rails.root, 'public', "test.jpg")

file = Files::File.new("upload.jpg")
file.mkdir_parents = true
file.write(File.open(dir))
file.close
> nil
```

But when I tried `Ruby 2.7.3` with same code

### Gemfile
```
ruby '2.7.3'

gem 'rails', '~> 6.1.3', '>= 6.1.3.2'
```

```
dir = File.join(Rails.root, 'public', "test.jpg")

file = Files::File.new("upload.jpg")
file.mkdir_parents = true
file.write(File.open(dir))
file.close

TypeError: no implicit conversion of Symbol into Integer
from /Users/***/.rvm/gems/ruby-2.7.3/gems/files.com-1.0.43/lib/files.com/models/file_part_upload.rb:64:in `partsize'
```

**Comment by files-elizabeth** [comment]
Hi @ChunAllen we have a support ticket opened up for you in our system, and we'll provide follow-up information there as it becomes available.
