### ISSUE TITLE
Filter by question

### ISSUE THREAD

**Issue by SerKnight** [Files-com/files-sdk-ruby#19]
`filter (string): If specified, will filter folders/files list by this string. Wildcards of * and ? are acceptable here.`

Just wanted to confirm that the filter functionality is strictly by string.

I am looking to query all files after a certain date, can you recommend a path?

**Comment by SerKnight** [comment]
https://github.com/Files-com/files-sdk-ruby/blob/a17666133032aff7a0609c825f638273e8e436de/docs/folder.md#parameters

**Comment by bombino** [comment]
We do support sorting by the last modified at.  Use `sort_by: { modified_at_datetime: :desc }`

**Comment by SerKnight** [comment]
So I'm not seeing any change in API response and I don't believe I found anywhere in site admin UI to view API logs.

```ruby
Files::Folder.list_for(ep_dir.path).each do |ep_file|
  # code
```
![Screen Shot 2022-08-23 at 2 18 00 PM](https://user-images.githubusercontent.com/2935387/186257564-29fce8bd-fd88-4118-8313-6897c6cd339d.png)

```ruby
Files::Folder.list_for(ep_dir.path, sort_by: { modified_at_datetime: :desc }).each do |ep_file|
  # would expect files sorted by most recent

```
![Screen Shot 2022-08-23 at 2 18 25 PM](https://user-images.githubusercontent.com/2935387/186257625-1fb461e5-46f2-474f-bc9e-a3ddd7b11a8a.png)

Both options seem to return the directories oldest files first. I've also tried the pagination param with a similar lack of results.

```ruby
Files::Folder.list_for(ep_dir.path, per_page: 5).each do |ep_file|
  # would expect only 5 files
```
![Screen Shot 2022-08-23 at 2 20 12 PM](https://user-images.githubusercontent.com/2935387/186257880-899fbb77-93d3-41d9-8712-43f872c38f9c.png)

Thanks for reply, let me know advice on troubleshooting. I can also try the JS or Python sdks?

**Comment by bombino** [comment]
Thanks for your patience; someone internal will reply with the right solution soon.

**Comment by SerKnight** [comment]
Support emailed me and I was able to get properly sorted with the following queries. Thanks team - sorry I must have had my wires crossed before

```ruby
Files::Folder.list_for("", sort_by: { modified_at_datetime: :desc }).each { |f| puts "#{f.type} #{f.path}" }
```

<img width="449" alt="Screen Shot 2022-08-31 at 11 31 58 AM" src="https://user-images.githubusercontent.com/2935387/187742497-9bd4cc32-46d3-4f98-893f-d9b53d4716de.png">
