### ISSUE TITLE
Files with spaces

### ISSUE THREAD

**Issue by cantyoudobetter** [Files-com/files-sdk-ruby#21]
The ruby client fails when working with files with spaces.  This can be repeated by putting a text file with a space in the name and then download and run file.read using the client.

Also, the file.rewind function needs to be properly implemented.  The Gem only allows one read.

**Comment by Files-Michael** [comment]
Thank you, we have received your support request. I have included the details you've provided here, so we will close this issue and continue the conversation on that thread.
